# Solvers benchmark on the `Riboflavin` data set

The data set can be downloaded from <https://www.annualreviews.org/doi/suppl/10.1146/annurev-statistics-022513-115545>.

The solvers (except our `path_solver`) were coded by Larsson et al. for the benchmark of their paper *Coordinate Descent for SLOPE*; their code is available at <https://github.com/jolars/slopecd> and needs to be installed to run the simulations here.

In [1]:
import sys
import numpy as np
import pandas as pd
from timeit import repeat

sys.path.append('../..')
from modules import path_solver, dual_sorted_L1_norm as dual_norm
from slope.solvers import prox_grad, admm, hybrid_cd #, newt_alm, oracle_cd

In [2]:
# Import of the data set
ribo = pd.read_csv('../datasets/riboflavin.csv', sep=',', index_col=0).T
data = ribo.drop(columns='q_RIBFLV')
target = ribo['q_RIBFLV']

In [3]:
# Setting (and data standardization)
X = data.to_numpy(dtype=float)
X_mean = X.mean(axis=0)
X_std = X.std(axis=0, ddof=0)
X = (X - X_mean) / X_std

y = target.to_numpy(dtype=float)
y_mean = y.mean()
y = y - y_mean 

Lambda = np.linspace(4,1,X.shape[-1],dtype=float)

In [4]:
# # Numba compilation
# _ = path_solver(X, y, Lambda, k_max=0., rtol_pattern=1e-6, atol_pattern = 1e-6, rtol_gamma=1e-6, split_max=1e1, log=0)
# _ = hybrid_cd(X, y, Lambda, fit_intercept=False, tol=1e-1)
# # _ = oracle_cd(X, y, Lambda, fit_intercept=False, tol=1e-1)
# _ = admm(X, y, Lambda, fit_intercept=False, rho=100, adaptive_rho=False, tol=1e-1)
# # _ = newt_alm(X, y, Lambda, fit_intercept=False, tol=1e-1)
# _ = prox_grad(X, y, Lambda, fit_intercept=False, tol=1e-1)

In [5]:
# Check-up and numba compilation
ratio = 0.5; gamma = ratio*dual_norm(X.T@y, Lambda)
nb_loops = 1; nb_runs = 1

# FISTA
sol, intercept, primals, gaps, times = prox_grad(X, y, gamma/X.shape[0]*Lambda, fit_intercept=False, fista=True, tol=1e-12/X.shape[0], max_epochs=1_000_000)
time_fista =np.mean(repeat('prox_grad(X, y, gamma/X.shape[0]*Lambda, fit_intercept=False, fista=True, tol=1e-12/X.shape[0], max_epochs=1_000_000)',
                   repeat=nb_runs, number=nb_loops, globals=globals()))/nb_loops
print(f'FISTA: {time_fista:.2e}s')
print(sol, X.shape[0]*primals[-1], X.shape[0]*gaps[-1], '\n')

# Anderson PGD
sol, intercept, primals, gaps, times = prox_grad(X, y, gamma/X.shape[0]*Lambda, fit_intercept=False, anderson=True, tol=1e-12/X.shape[0], max_epochs=1_000_000)
time_pgd =np.mean(repeat('prox_grad(X, y, gamma/X.shape[0]*Lambda, fit_intercept=False, anderson=True, tol=1e-12/X.shape[0], max_epochs=1_000_000)',
                   repeat=nb_runs, number=nb_loops, globals=globals()))/nb_loops
print(f'Anderson PGD: {time_pgd:.2e}s')
print(sol, X.shape[0]*primals[-1], X.shape[0]*gaps[-1], '\n')

# ADMM (with rho=100)
sol, intercept, primals, gaps, times = admm(X, y, gamma/X.shape[0]*Lambda, fit_intercept=False, rho=100, adaptive_rho=False, tol=1e-12/X.shape[0], max_epochs=1_000_000)
time_admm =np.mean(repeat('admm(X, y, gamma/X.shape[0]*Lambda, fit_intercept=False, rho=100, adaptive_rho=False, tol=1e-12/X.shape[0], max_epochs=1_000_000)',
                   repeat=nb_runs, number=nb_loops, globals=globals()))/nb_loops
print(f'ADMM: {time_admm:.2e}s')
print(sol, X.shape[0]*primals[-1], X.shape[0]*gaps[-1], '\n')

# hybrid CD
sol, intercept, primals, gaps, times, n_cluster = hybrid_cd(X, y, gamma/X.shape[0]*Lambda, fit_intercept=False, tol=1e-12/X.shape[0])
time_cd =np.mean(repeat('hybrid_cd(X, y, gamma/X.shape[0]*Lambda, fit_intercept=False, tol=1e-12/X.shape[0])',
                   repeat=nb_runs, number=nb_loops, globals=globals()))/nb_loops
print(f'hybrid CD: {time_cd:.2e}s')
print(sol, X.shape[0]*primals[-1], X.shape[0]*gaps[-1], '\n')

# path (our)
sol, (primal, gap), k = path_solver(X, y, gamma*Lambda, k_max=1e3, rtol_pattern=1e-10, atol_pattern = 1e-10, rtol_gamma=1e-10, split_max=1e1, log=0)
time_path =np.mean(repeat('path_solver(X, y, gamma*Lambda, k_max=1e3, rtol_pattern=1e-10, atol_pattern = 1e-10, rtol_gamma=1e-10, split_max=1e1, log=0)',
                   repeat=nb_runs, number=nb_loops, globals=globals()))/nb_loops
print(f'path (our): {time_path:.2e}s')
print(sol, primal, gap, '\n')

# # oracle CD
# sol, intercept, primals, gaps, times = oracle_cd(X, y, gamma/X.shape[0]*Lambda, fit_intercept=False, tol=1e-12)
# print(sol, X.shape[0]*primals[-1], gaps[-1])
# time_oracle =np.mean(repeat('oracle_cd(X, y, gamma/X.shape[0]*Lambda, fit_intercept=False, tol=1e-12)',
#                    repeat=nb_runs, number=nb_loops, globals=globals()))/nb_loops
# print(f'oracle CD: {time_oracle:.2e}s')

# # Newt-ALM
# sol, intercept, primals, gaps, times = newt_alm(X, y, gamma/X.shape[0]*Lambda, fit_intercept=False, tol=1e-12)
# print(sol, X.shape[0]*primals[-1], gaps[-1])
# time_newt_alm =np.mean(repeat('newt_alm(X, y, gamma/X.shape[0]*Lambda, fit_intercept=False, tol=1e-12)',
#                    repeat=nb_runs, number=nb_loops, globals=globals()))/nb_loops
# print(f'Newt-ALM: {time_newt_alm:.2e}s')

FISTA: 1.10e+02s
[ 0. -0. -0. ...  0. -0.  0.] 24.573028434631915 7.251976796851523e-13 



/Users/xdupuis/miniconda3/envs/slopecd/lib/python3.9/site-packages/slope/solvers/pgd.py:67: RuntimeWarning: divide by zero encountered in true_divide
  c = coefs / coefs.sum()
/Users/xdupuis/miniconda3/envs/slopecd/lib/python3.9/site-packages/slope/solvers/pgd.py:67: RuntimeWarning: invalid value encountered in true_divide
  c = coefs / coefs.sum()
/Users/xdupuis/miniconda3/envs/slopecd/lib/python3.9/site-packages/slope/solvers/pgd.py:68: RuntimeWarning: invalid value encountered in multiply
  w_acc = np.sum(last_K_w[:-1] * c[:, None], axis=0)
/Users/xdupuis/miniconda3/envs/slopecd/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


Anderson PGD: 1.58e+01s
[ 0. -0. -0. ...  0. -0.  0.] 24.57302843463191 7.567280135845067e-13 

ADMM: 6.51e+02s
[ 6.24500451e-17  1.38777878e-16  9.71445147e-17 ...  6.93889390e-17
  8.58688121e-17 -2.77555756e-17] 24.573028434635113 3.2318592246838307e-12 



/Users/xdupuis/miniconda3/envs/slopecd/lib/python3.9/site-packages/slope/solvers/hybrid.py:45: NumbaPerformanceWarning: '@' is faster on contiguous arrays, called on (Array(float64, 1, 'A', False, aligned=True), Array(float64, 1, 'A', False, aligned=True))
  XTX[ind] = (X[:, ind] @ X[:, ind]) / n_samples


hybrid CD: 4.00e-02s
[ 0. -0. -0. ...  0. -0.  0.] 24.57302843463192 3.1530333899354446e-14 



/Users/xdupuis/Research/slope-path/github/experiments/solvers_benchmarks/../../modules/solvers.py:89: NumbaExperimentalFeatureWarning: Use of isinstance() detected. This is an experimental feature.
  m = face_pattern(grad, Lambda, rtol_pattern, atol_pattern)


path (our): 3.75e-02s
[0. 0. 0. ... 0. 0. 0.] 24.573028434631908 0.0 



In [11]:
benchmark = pd.DataFrame({},index=['Anderson PGD', 'hybrid CD', 'path (our)'])
benchmark.columns.name='gamma / gamma_max'

In [12]:
# Benchmark
nb_loops = 100; nb_runs = 7 

# for ratio in [0.5, 0.1, 0.02]:
gamma = ratio*dual_norm(X.T@y, Lambda)
# time_fista =np.mean(repeat('prox_grad(X, y, gamma/X.shape[0]*Lambda, fit_intercept=False, fista=True, tol=1e-12/X.shape[0], max_epochs=100_000)',
#                     repeat=nb_runs, number=nb_loops, globals=globals()))/nb_loops
time_pgd =np.mean(repeat('prox_grad(X, y, gamma/X.shape[0]*Lambda, fit_intercept=False, anderson=True, tol=1e-12/X.shape[0], max_epochs=20_000)',
                  repeat=nb_runs, number=nb_loops, globals=globals()))/nb_loops
# time_admm =np.mean(repeat('admm(X, y, gamma/X.shape[0]*Lambda, fit_intercept=False, rho=100, adaptive_rho=False, tol=1e-12/X.shape[0], max_epochs=100_000)',
#                     repeat=nb_runs, number=nb_loops, globals=globals()))/nb_loops
time_cd =np.mean(repeat('hybrid_cd(X, y, gamma/X.shape[0]*Lambda, fit_intercept=False, tol=1e-12/X.shape[0])',
                    repeat=nb_runs, number=nb_loops, globals=globals()))/nb_loops
time_path =np.mean(repeat('path_solver(X, y, gamma*Lambda, k_max=1e3, rtol_pattern=1e-10, atol_pattern = 1e-10, rtol_gamma=1e-10, split_max=1e1, log=0)',
                    repeat=nb_runs, number=nb_loops, globals=globals()))/nb_loops
benchmark[f'{ratio}'] = [time_pgd, time_cd, time_path]


/Users/xdupuis/miniconda3/envs/slopecd/lib/python3.9/site-packages/slope/solvers/pgd.py:67: RuntimeWarning: divide by zero encountered in true_divide
  c = coefs / coefs.sum()
/Users/xdupuis/miniconda3/envs/slopecd/lib/python3.9/site-packages/slope/solvers/pgd.py:67: RuntimeWarning: invalid value encountered in true_divide
  c = coefs / coefs.sum()
/Users/xdupuis/miniconda3/envs/slopecd/lib/python3.9/site-packages/slope/solvers/pgd.py:68: RuntimeWarning: invalid value encountered in multiply
  w_acc = np.sum(last_K_w[:-1] * c[:, None], axis=0)
/Users/xdupuis/miniconda3/envs/slopecd/lib/python3.9/site-packages/numpy/core/fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


gamma / gamma_max      0.5
Anderson PGD      1.45e+01
hybrid CD         4.19e-02
path (our)        3.83e-02

In [ ]:
with pd.option_context('display.float_format', '{:,.2e}'.format):
    display(benchmark)

In [13]:
benchmark.to_csv('../results/riboflavin_benchmark.csv', float_format='{:.2e}'.format, mode='a')

In [14]:
with open('../results/riboflavin_benchmark.txt', 'a') as f:
                f.write(benchmark.to_latex(float_format='{:.2e}'.format))